"""add post

Revision ID: bce597710008
Revises: ff19bfe9643d
Create Date: 2024-06-25 18:54:08.057935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce597710008'
down_revision = 'ff19bfe9643d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poste', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poste_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poste', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poste_timestamp'))

    op.drop_table('poste')
    # ### end Alembic commands ###
