"""Added img field to User model

Revision ID: ff19bfe9643d
Revises: 5a6d8db3e187
Create Date: 2024-06-22 12:01:43.002045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff19bfe9643d'
down_revision = '5a6d8db3e187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
